### ISSUE TITLE
--health-cmd ?

### ISSUE THREAD

**Issue by itsalljustdata** [jittering/traefik-kop#11]
I (wherever possible) monitor my containers with the excellent willfarrell/autoheal docker container.  What would be a suitable --health-cmd for traefik-cop to test it's state of health?

**Comment by chetan** [comment]
@TheFlyingBadger the program operates fairly simply -- it continuously watches the docker API for any changes and when one is detected, tries to write those changes to redis. If there is any unexpected (unhandled) error in processing the config change or writing it into redis, the program will panic and exit with an error. In that situation, the container should automatically restart.

Otherwise, if the container is running, it should be working. I haven't seen a situation so far where it stopped working for some unknown reason and needed to be manually restarted. Hope that helps.
